//! Status verdicts matched against the reference
//! (compat/golden/status.json, generated by
//! compat/tools/gen_status_golden.py).

use std::path::PathBuf;

use chrono::{DateTime, Utc};
use ragmonk_core::errors::LockOwner;
use ragmonk_indexing::progress::{progress_from_value, IndexProgress};
use ragmonk_indexing::status::{
    derive_health, derive_index_state, derive_problems, indexer_state_from, merge_queue_stats,
    LockView,
};
use serde_json::Value;

fn golden() -> Value {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../compat/golden/status.json");
    serde_json::from_str(&std::fs::read_to_string(p).unwrap()).unwrap()
}

fn owner(v: &Value) -> Option<LockOwner> {
    v.as_object().map(|o| {
        let s = |k: &str| o.get(k).and_then(Value::as_str).map(str::to_owned);
        LockOwner {
            present: true,
            pid: o.get("pid").and_then(Value::as_i64).map(|p| p.to_string()),
            operation: s("operation"),
            source_id: s("source_id"),
            acquired_at: s("acquired_at"),
            hostname: s("hostname"),
        }
    })
}

#[test]
fn indexer_state_matches_reference_scenarios() {
    let g = golden();
    let now: DateTime<Utc> = DateTime::parse_from_rfc3339(g["now"].as_str().unwrap())
        .unwrap()
        .into();
    let threshold = g["threshold"].as_f64().unwrap();
    for case in g["indexer"].as_array().unwrap() {
        let state = match case["lock"].as_str().unwrap() {
            "free" => "free",
            "held" => "held",
            _ => "unknown",
        };
        let lock = LockView {
            state,
            owner: owner(&case["owner"]),
        };
        let snapshot: Option<IndexProgress> = case["snapshot"].as_object().map(|o| {
            let mut v = Value::Object(o.clone());
            v["schema_version"] = 1.into();
            progress_from_value(&v).unwrap()
        });
        let alive: Vec<i64> = case["alive"]
            .as_array()
            .unwrap()
            .iter()
            .map(|p| p.as_i64().unwrap())
            .collect();
        let got = indexer_state_from(
            &lock,
            snapshot.as_ref(),
            |p| alive.contains(&p),
            threshold,
            now,
        );
        assert_eq!(got, case["expected"], "scenario {}", case["name"]);
    }
}

#[test]
fn index_state_problems_health_and_merge_match_reference() {
    let g = golden();
    for case in g["index_state"].as_array().unwrap() {
        let i = &case["input"];
        let got = derive_index_state(
            i["access_state"].as_str().unwrap(),
            &i["queue"],
            i["failed_files"].as_i64().unwrap(),
            i["last_error"].as_str(),
            i["last_scan_at"].as_str(),
            &i["indexer"],
            "s",
        );
        assert_eq!(got, case["expected"], "{i}");
    }
    for case in g["problems"].as_array().unwrap() {
        let i = &case["input"];
        let problems = derive_problems(
            i["sources"].as_array().unwrap(),
            &i["indexer"],
            &i["backend"],
            &i["queue"],
        );
        assert_eq!(Value::Array(problems.clone()), case["problems"], "{i}");
        assert_eq!(derive_health(&problems), case["health"]);
    }
    for case in g["merge"].as_array().unwrap() {
        assert_eq!(
            merge_queue_stats(case["input"].as_array().unwrap()),
            case["expected"]
        );
    }
}

#[test]
fn progress_snapshot_has_the_reference_keys() {
    let g = golden();
    let mut want: Vec<String> = serde_json::from_value(g["progress_fields"].clone()).unwrap();
    let v = serde_json::to_value(IndexProgress::default()).unwrap();
    let mut got: Vec<String> = v.as_object().unwrap().keys().cloned().collect();
    want.sort();
    got.sort();
    assert_eq!(got, want);
}
